FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/
COPY srt-resume.html /usr/share/nginx/html/
COPY resume.css /usr/share/nginx/html/
COPY srt.png /usr/share/nginx/html/
COPY ttab.png /usr/share/nginx/html/